# .goreleaser.yml
# Build customization
builds:
  - main: .
    binary: portal
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    amd64: 64-bit
    darwin: macOS
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"